#!/bin/sh

# Helper script that reads /etc/default/dump978-fa
# and either starts dump1090-fa with the configured
# arguments, or exits with status 64 to tell systemd
# not to auto-restart the service.

if [ -f /etc/default/dump978-fa ]
then
    . /etc/default/dump978-fa
fi

if [ -f /var/cache/piaware/location.env ]
then
    . /var/cache/piaware/location.env
fi

if [ "x$ENABLED" != "xyes" ]
then
    echo "dump978-fa not enabled in /etc/default/dump978-fa" >&2
    exit 64
fi

if [ -n "$LAT" -a -n "$LON" ]
then
    POSITION="--lat $LAT --lon $LON"
fi

exec /usr/bin/dump978-fa \
     $RECEIVER_OPTIONS $DECODER_OPTIONS $NET_OPTIONS \
     "$@"
# exec failed, do not restart
exit 64
